### ISSUE TITLE
Cannot update or delete documents with an Uuid

### ISSUE THREAD

**Issue by tomdoo** [meilisearch/meilisearch-symfony#109]
Hi!
I'm using this type of IDs in my entities :

```
/**
 * @ORM\Id
 * @ORM\GeneratedValue(strategy="UUID")
 * @ORM\Column(type="uuid")
 */
private $id;
```

On update or remove I get an MeiliSearch\Exceptions\InvalidArgumentException in this method :

```
private function assertValidDocumentId($documentId): void
{
    if (!\is_string($documentId) && !\is_int($documentId)) {
        throw InvalidArgumentException::invalidType('documentId', ['string', 'int']);
    }

    if (\is_string($documentId) && '' === trim($documentId)) {
        throw InvalidArgumentException::emptyArgument('documentId');
    }
}
```

**Comment by curquiza** [comment]
Hello @tomdoo!

Can you give in which context you have this error? What kind of document id triggers this problem?

**Comment by tomdoo** [comment]
This error occurs when I persist entities with an UuidV4 primary key.
It fails on MeiliSearch\Bundle::remove() because the ID send is an object instead of int|string.

**Comment by curquiza** [comment]
Add a test with this specific situation would be perfect then :)

**Comment by tomdoo** [comment]
I added the tests.

There was also an issue in MeiliSearchService::search. For a reason I don't know this doesn't works with generic objects

```
$entity = $repo->findOneBy(['id' => $id]);
```

I replaced it with, it's also better if your identifier is not named "id"

```
$entity = $repo->find($id);
```
