### ISSUE TITLE
Delete command

### ISSUE THREAD

**Issue by tomdoo** [meilisearch/meilisearch-symfony#114]
**Description**
A command like import or clear to delete indexes.

**Basic example**
To complety delete one or more indexes

`php bin/console meili:delete --indices=posts,comments`

**Other**
If you are interrested I can make a pull request, I have already coded this command.

**Comment by curquiza** [comment]
Hello again @tomdoo!

I'm interested in reviewing your PR for this addition :D

**Comment by tomdoo** [comment]
https://github.com/meilisearch/meilisearch-symfony/pull/115
