### ISSUE TITLE
Add test to check the value of "prefix"

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-symfony#14]
Following this issue (#12) and this PR (#13), we need to add test checking the value of `prefix` (in `meili_search.yml` file), especially testing the empty value.

Any suggestions to implement these tests?

**Comment by codedge** [comment]
There seems to be an existing test to check if an index could be cleared - https://github.com/meilisearch/meilisearch-symfony/blob/main/tests/TestCase/CommandsTest.php#L66

Anything else that should be tested in this ticket here or can this be closed?

**Comment by curquiza** [comment]
Indeed!! Closing :)
