### ISSUE TITLE
I've got "Notice: Undefined index: errorCode" on excecuting bin/console meili:import command

### ISSUE THREAD

**Issue by 676767ap** [meilisearch/meilisearch-symfony#152]
On excecuting bin/console meili:import command i've got this:
```
In HandlesIndex.php line 64:
                                      
  Notice: Undefined index: errorCode  
```
My meili_search.yaml
```
meili_search:
    indices:
        - name: docs
          class: App\Entity\SearchRes
          enable_serializer_groups: true
```
SearchRes.php entity:
```
<?php

namespace App\Entity;
use App\Repository\SearchResRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=SearchResRepository::class)
 */
class SearchRes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $entityType;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getEntityType(): ?string
    {
        return $this->entityType;
    }

    public function setEntityType(?string $entityType): self
    {
        $this->entityType = $entityType;

        return $this;
    }
}
```
in .env:
```
MEILISEARCH_URL=http://127.0.0.1:7700
MEILISEARCH_API_KEY=Y0urVery-S3cureAp1K3y
```
Symfony 4, Ubuntu 21.10, PHP 7.4

**Comment by curquiza** [comment]
If you use MeilISearch v0.24.0, please use:
- meilsearch-php v0.20.0 https://github.com/meilisearch/meilisearch-php/releases/tag/v0.20.0
- search-bundle v0.6.0 https://github.com/meilisearch/meilisearch-symfony/releases/tag/v0.6.0

**Comment by 676767ap** [comment]
Thanks a lot! Unfortunately i cannot use those versions due to confilts with other old bundles. I'll try to downgrade MeilISearch itself.

**Comment by curquiza** [comment]
Which conflict do you have? :(

**Comment by 676767ap** [comment]
Many!)))) With old Sonata-project + Doctrine ORM mostly it unsolvable

**Comment by 676767ap** [comment]
Could you please tell me what version of meilisearch will work with "meilisearch/search-bundle": "^0.2.6" and "meilisearch/meilisearch-php": "v0.16.0" ?

**Comment by curquiza** [comment]
I would say MeiliSearch v0.20.0 or older...
Do we have a too old (or too new?) doctrine-bundle dependency in our composer.json?

**Comment by brunoocasali** [comment]
@676767ap and @curquiza I had this exact same problem when I was trying this bundle.

My problem was regarding my Meilisearch server version being too much up to date (v0.26.1) using an old `search-bundle`, and `meilisearch-php`.

So, @676767ap I think your problem will be solved by doing what @curquiza said, updating all or downgrading all. 
I'll close this issue, but feel free to open new ones!

Thanks a lot for using Meilisearch ❤️

**Comment by Laguigue** [comment]
Hello, i just ran through the same problem: i installed the bundle + settup Meilisearch via docker (https://hub.docker.com/r/getmeili/meilisearch/tags). I managed to get it fixed by changing my docker image getmeili/meilisearch:latest to getmeili/meilisearch:v0.20.0 But why close this issue ? It is still a major bug for any people who will install the bundle and Meilisearch at last version. Any ideas when this will be fixed ?
