### ISSUE TITLE
Add raw search?

### ISSUE THREAD

**Issue by arkste** [meilisearch/meilisearch-symfony#17]
Looking at [`MeiliSearchService->search()`](https://github.com/meilisearch/meilisearch-symfony/blob/master/src/Services/MeiliSearchService.php#L207) it requires an `ObjectManager`. 

While i do get the idea behind it, there should be a way to call the raw results without getting the entities from the database, something like this:

```php
    public function searchRaw(
        string $className,
        string $query = '',
        array $requestOptions = []
    ): array {
        $this->assertIsSearchable($className);

        return $this->engine->search($query, $this->searchableAs($className), $requestOptions);
    }
```

Performance-wise its faster getting the data directly from MS than waiting for the "real" entities from MySQL. 

What do you think?

**Comment by althaus** [comment]
I've just made some first steps using the bundle and I'd prefer to use the raw querying and hits to display the results. The performance overhead with querying and hydrating the found entities is massive compared to using the raw data.

**Comment by curquiza** [comment]
Hello! This is indeed a good idea, and we are really open to any PR :)

**Comment by althaus** [comment]
> 
> 
> Hello! This is indeed a good idea, and we are really open to any PR :)

I'll check it out.
