### ISSUE TITLE
Please provide a small example for search with service

### ISSUE THREAD

**Issue by 3PSY0N** [meilisearch/meilisearch-symfony#191]
Hello 

I'd like to make a basic search for my icons
Here's my code : 
```php
    #[Route('/search', name: 'app_search')]
    public function search(SearchService $searchService, Request $request, EntityManagerInterface $entityManager)
    {
        $searchQuery = $request->query->get('q');
        if (empty($searchQuery)) return $this->redirectToRoute('app_home');

        $hits = $searchService->rawSearch(Icon::class, $searchQuery)["hits"];
        dd($hits);
    }
```

This isn't optimal, I'm sure there is a way to search directly but I don't found anything in the documentation. 

When I do this, I found 0 hits : 
```php
$hits = $searchService->search($entityManager, Icon::class, $searchQuery)
```

Can you provide a small example to how to do a basic search **with SearchService**

Thank you

**Comment by brunoocasali** [comment]
Hi, @3PSY0N thanks for using Meilisearch! 

Before entering your specific request, did you index the data? For example, can you usually search through the documents in a CURL/Postman request?

**Comment by brunoocasali** [comment]
Hi @3PSY0N I've created a small example of how you can use this bundle here: https://github.com/meilisearch/meilisearch-symfony/wiki/Searching-with-Meilisearch-Bundle

Let me know if you need anything!

Thanks for using Meilisearch ❤️
