### ISSUE TITLE
Wiki: Change 'attributesForFaceting' to 'searchableAttributes'

### ISSUE THREAD

**Issue by daFish** [meilisearch/meilisearch-symfony#206]
**Description**
The wiki page https://github.com/meilisearch/meilisearch-symfony/wiki/configure-settings uses the outdated setting `attributesForFaceting`. This will lead to an exception when updating the indices.
To make it work, the key needs to be `searchableAttributes`.

**Comment by brunoocasali** [comment]
Thanks for your report @daFish it is done! 🤘
