### ISSUE TITLE
Case mismatch between loaded and declared class names: "MeiliSearch\Client" vs "Meilisearch\Client".

### ISSUE THREAD

**Issue by wucherpfennig** [meilisearch/meilisearch-symfony#215]
**Description**
See latest release of https://github.com/meilisearch/meilisearch-php/releases/tag/v0.26.1

**Environment (please complete the following information):**
- Meilisearch version: 0.26.1
- meilisearch-symfony version: 0.9
- symfony 6.2.2

![grafik](https://user-images.githubusercontent.com/3634653/208197796-9d18249f-32f0-46fc-95d8-a598606d3f10.png)

**Comment by mmachatschek** [comment]
Good lord, Symfony is applying custom logic to namespace and class casings 🙄

**Comment by brunoocasali** [comment]
@mmachatschek can you give a look at #217? I'm also thinking of a way to handle the `meili_search.yaml`/`meilisearch.yml` change to not expose it as a breaking change.

**Comment by brunoocasali** [comment]
The bug is fixed and released as 0.10.0 unfortunately, I didn't have enough time to understand better how I could solve the `meili_search:` to `meilisearch:` root key in the config file automatically. If someone does, I would love to learn that :)

Sorry for the inconvenience.
