### ISSUE TITLE
Multi language index per language

### ISSUE THREAD

**Issue by tonyellow** [meilisearch/meilisearch-symfony#222]
**Description**
My project is multi language. I have a product entity containing data in 4 languages. I would like to create an index per language. 

**Expected behavior**
In my normalizer I would like to know the name of the index, this way I could extract the language from the index name and feed the correct language to the index. In meilisearch.yaml I would do this:

meilisearch:
  indices:
    -   name: products_en
        class: App\Entity\Product
        index_if: isSearchable
    -   name: products_fr
        class: App\Entity\Product
        index_if: isSearchable

**Current behavior**
There is no way to retrieve the index name in the normalizer. 

I could not find many information on multi language indexing. Maybe there is a better approach to multi language indexing than my suggested approach?

**Comment by brunoocasali** [comment]
Hi @tonyellow 

Have you tried doing it in only one index and then using [`filterableAttributes`](https://docs.meilisearch.com/reference/api/settings.html#filterable-attributes)? 

Then you can use the filters in your app https://docs.meilisearch.com/learn/getting_started/filtering_and_sorting.html#filtering

`$client->index('meteorites')->search('', ['filter' => 'language = en']);`

I never helped anyone with this kind of context. Maybe @oluademola has something else to share?

**Comment by tonyellow** [comment]
Thanks bruno, I will try to do it your way and and create all the language attributes in the index.

**Comment by brunoocasali** [comment]
I assume it did work for you, so I'm going to close this issue. Feel free to reopen it!

Thanks for using Meilisearch!

**Comment by cyrill-intersim** [comment]
Hi everyone

I'm facing the same challenge. While distinguishing languages by `filterableAttributes` could work, Meilisearch recommends to [create separate indexes for multiple language](https://www.meilisearch.com/docs/learn/indexing/indexing_best_practices#create-separate-indexes-for-multiple-languages). Did you find a solution to this problem @tonyellow or do you have any experience to share?

**Comment by tonyellow** [comment]
@cyrill-intersim  I ended up using just a single index and storing my translations in an array. You can search for a specific language by filtering on the array key. Alternatively, you could also create separate fields for each language. It’s quite flexible!
