### ISSUE TITLE
Option for passing memory-limit to meili:import command

### ISSUE THREAD

**Issue by Seesicht-IT** [meilisearch/meilisearch-symfony#229]
**Description**
First of all, thanks for creating this bundle!

I created a test-setup where I imported around 700.000 records into the search-index of Meilisearch. While doing so, I realized that the import requires more PHP memory than regular operations / my regular PHP memory_limit configuration. To successfully import the data into the search-index, I had to increase the memory_limit to 3072M.

I was also testing TNTSearch (https://github.com/teamtnt/tntsearch) with the same data-set and for exporting / creating the index, 512M were sufficient. However, TNTSearch is not using Doctrine.

I will look into the memory consumption in more detail, but I would suggest having the possibility to pass the memory_limit as a parameter to the command. E.g.
`php bin/console meili:import --memory-limit=<memory in MB>`

And then use this value to ini_set the memory_limit in the execute function:
`ini_set('memory_limit', $memoryLimit);`

With this approach, regular updates of the index would run with the general memory_limt. And full imports could be run with a specific memory setting passed to the command.

**Comment by Seesicht-IT** [comment]
A possible solution could look like this:

src/Command/MeilisearchImportCommand.php

```
->addOption(
    'memory-limit',
    'm',
    InputOption::VALUE_REQUIRED,
    'Memory limt (in MB) to run the import command',
    trim(ini_get('memory_limit'), 'M')
)
```

```
protected function execute(InputInterface $input, OutputInterface $output): int
{
    ini_set('memory_limit', $input->getOption('memory-limit').'M');
    $indexes = $this->getEntitiesFromArgs($input, $output);
    $config = $this->searchService->getConfiguration();
    ...
```

**Comment by norkunas** [comment]
> I will look into the memory consumption in more detail, but I would suggest having the possibility to pass the memory_limit as a parameter to the command. E.g. `php bin/console meili:import --memory-limit=<memory in MB>`
> 
> And then use this value to ini_set the memory_limit in the execute function: `ini_set('memory_limit', $memoryLimit);`

You can run as `php -d memory_limit=128M bin/console meili:import`

**Comment by Seesicht-IT** [comment]
Thanks for the tip. No need for another parameter in the command...
