### ISSUE TITLE
Entity mapping not working correctly?

### ISSUE THREAD

**Issue by Zeichen32** [meilisearch/meilisearch-symfony#23]
I have try this bundle in a new project, but i cannot get it to work properly.

Maybe i have found a bug, in the MeiliSearchService at linte 218 their is a for-each to iterate over the ids.

```
$test= $searchService->search($this->getDoctrine()->getManager(), Test::class, 'hello');
```

https://github.com/meilisearch/meilisearch-symfony/blob/master/src/Services/MeiliSearchService.php#L218
```php
foreach ($ids as $objectID) {
```

But if i do a var_dump on the $ids array, the array looks like:
```
array (size=7)
  'hits' => 
    array (size=20)
      0 => 
        array (size=7)
          'objectID' => int 7
          'id' => int 7
          'tag' => string 'hello' (length=5)
          'context' => null
          'actions' => null
          'parameters' => null
          'patterns' => 
            array (size=6)
              ...
      1 => 
```

If i change the for-each loop to the following, all is working as expected:
```php
foreach ($ids['hits'] as $objectID) {
```

Is it a bug, or i am doing something wrong? 
If it is a bug, i can create a PR to fix the issue.

**Comment by emulienfou** [comment]
Hi @Zeichen32 currently working on fixing this. It seems there is clearly an issue with the code.   
Will add some test case to check it work perfectly.

**Comment by curquiza** [comment]
Hello @kermitsxb, @emulienfou seems not have found the time fix this issue, even if he's assigned, feel free (you or anyone else) to open a PR to fix it, it would be awesome 👍 
Sorry about this, and thanks for your patience! 😄

**Comment by kermitsxb** [comment]
I proposed PR #33 with a small fix

**Comment by emulienfou** [comment]
Thanks @kermitsxb to taking the time to fix this, did not had time to work on it recently

**Comment by curquiza** [comment]
Thanks a lot @kermitsxb!
