### ISSUE TITLE
Remove method in Engine not working properly

### ISSUE THREAD

**Issue by Zeichen32** [meilisearch/meilisearch-symfony#24]
The $objects variable contains an array of Ids, but the deleteDocument() method expect a single document id.
I think it must be change to deleteDocuments($objects)

https://github.com/meilisearch/meilisearch-symfony/blob/master/src/Engine.php#L109

```php
        foreach ($data as $indexName => $objects) {
            $result[$indexName] = $this->client
                ->getIndex($indexName)
                ->deleteDocument($objects);
        }
```

Edit: This issue will be fixed by #21

**Comment by emulienfou** [comment]
@Zeichen32 #21 has been merged fixing the issue
