### ISSUE TITLE
Inconsistency in how objects are normalized when indexing

### ISSUE THREAD

**Issue by mkilmanas** [meilisearch/meilisearch-symfony#245]
**Description**
It appears that objects are normalized differently when being indexed via CLI command and when it's done by doctrine event listener

**Expected behavior**
The records should be normalized the same way regardless of mechanism triggering the indexing of the entity

**Current behavior**
Normalization via CLI behaves differently (I have not investigated in detail what the differences are) than indexing via doctrine event listener (in turn triggered by the web/api request)

**Screenshots or Logs**
<img width="872" alt="Screenshot 2023-04-25 at 18 35 51" src="https://user-images.githubusercontent.com/392168/234329956-c11c7f3a-24c8-42fe-a5f5-ce36bcdc3f3d.png">
The 1st and 3rd results were indexed using CLI and the 2nd result is created by doctrine listener

**Environment (please complete the following information):**
- OS: Official meilisiearch docker image (v1.1.0)
- Meilisearch version: v1.1.0
- meilisearch-symfony version: v0.11.0
- Api Platform: v2.7.11
- Doctrine Bundle: v2.9.1
- PHP: 8.2.3
- Symfony: v6.2.8

**Workaround:**
For now I have implemented a custom Normalizer class to handle my entity, so that it produces consistent results

**Comment by brunoocasali** [comment]
Hi @mkilmanas, can you give me more details about your entity? How this `customer_identity` is created?

**Comment by brunoocasali** [comment]
I've created a use case to reproduce the behavior you've noticed, but I did not find anything strange when using my simple entity called `Page`.

Here is my test case: https://github.com/meilisearch/meilisearch-symfony/pull/249

I recommend checking how you handle the data in the serializer/normalizer to ensure nothing is happening in the middle. 
I'll close this. Feel free to reopen if you find any inconsistency in meilisearch-symfony data handling.

cheers,
