### ISSUE TITLE
Dynamic settings

### ISSUE THREAD

**Issue by norkunas** [meilisearch/meilisearch-symfony#248]
**Description**
Currently all index settings must be configured via bundle config and therefore they cannot be dynamic aka fetched from somewhere else.

**Basic example**
Not sure but maybe we could allow to declare setting as a service (not necessarily for all settings):
```
            settings:
                stopWords: '@App\Meilisearch\Stopwords'
                synonyms: '@App\Meilisearch\Synonyms'
```

**Other**
We have a resource in a database where our content managers store synonyms along with it so we need a simple solution to always fetch the up to date synonyms when indexing.

**Comment by brunoocasali** [comment]
I think it is a good idea @norkunas!
