### ISSUE TITLE
Refactor CommandsTest file

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-symfony#255]
Split CommandsTest file in multiple and contexted files, one file per kind of command under test.

The idea is to prevent having to update all the tests even when nothing was adequately touched. That happens because all those tests share the same setup (config file).

So, besides moving each test to each file, we should also update the config files and break them to improve maintainability. 

Related to #253

**Comment by norkunas** [comment]
Also instead of always touching CommandsTest when we try to test some new feature with indexing, we should probably have an Indexer service. Also it would assist in tests when you need to prepare an index before testing search in consumer app :)
