### ISSUE TITLE
[RFC] bump php to v8+ and Symfony to v5.4+

### ISSUE THREAD

**Issue by 94noni** [meilisearch/meilisearch-symfony#263]
Hi

both php v7 and symfony v4 are EOL to date 
Imho it will be great to upgrade this bundle with such minimum requirements

wdyt ?

---

- Symfony v5.4 LTS ([release map](https://symfony.com/releases#symfony-releases-calendar))
  - https://github.com/meilisearch/meilisearch-symfony/pull/265
  - https://github.com/meilisearch/meilisearch-symfony/pull/301 (supersede the above)
- PHP v8 ([release map](https://www.php.net/supported-versions.php))
  - Blocked, see https://github.com/meilisearch/meilisearch-symfony/issues/263#issuecomment-1591498511

**Comment by brunoocasali** [comment]
Hi! @94noni 

I'm ok with upgrading to Symfony v5.4 since it is the LTS. But the PHP v8 I'm planning to do it at the beginning of 2024. So it will trigger an update here as well.

You can provide a PR if you want. It will be much appreciated! 🦖

**Comment by 94noni** [comment]
Thx for reply, ok i will do my best to try to make symfony v5.4 upgrade alone
