### ISSUE TITLE
setting: "distinctAttribute" type inconsistency

### ISSUE THREAD

**Issue by Joepin8** [meilisearch/meilisearch-symfony#273]
**Description**
When trying to set the "distinctAttribute" setting, the bundle expects an array, while the meili search setting object expects a string value.

**Expected behavior**
When setting a string in the bundle's config, the value's type should not result in a type error.

**Current behavior**
Either a type error is thrown by the bundle or through meili search.

**Environment:**
- OS: Ubuntu 22.04
- Meilisearch version: v1.2.0
- meilisearch-symfony version: v0.13.0

**Comment by norkunas** [comment]
I'm working on a PR to properly define all settings config schema, but not sure when will finish it.
[WIP here](https://github.com/meilisearch/meilisearch-symfony/compare/main...norkunas:meilisearch-symfony:settings-config)

**Comment by Joepin8** [comment]
Okay, thanks for letting me know. Shall I close this issue then?

**Comment by norkunas** [comment]
You can leave it open :) Also #256 is related

**Comment by Joepin8** [comment]
Can I help to have this in the next release?

**Comment by curquiza** [comment]
Hello @Joepin8 
The help of the community is more than welcome here, feel free to open PRs 😊
