### ISSUE TITLE
Use PUT operation to update existing document(s)

### ISSUE THREAD

**Issue by daFish** [meilisearch/meilisearch-symfony#319]
**Description**
Inserting or updating exisiting documents is currently done with the POST request. This means exisiting documents are always replaced instead of updated. This should be either configurable or changes so that updates to existing documents are using PUT.

**Comment by norkunas** [comment]
What would be the difference then? All the document data is always sent so result would be the same, no?

**Comment by daFish** [comment]
The difference would the use of `PUT` to update the existing document whereas `POST` replaces the document in it's entirety. This leads to - in my case - unwanted side effects, e.g. a query-less search with filters omits the replaced document. Not so when the document has been properly updated.

**Comment by daFish** [comment]
Thanks for insights. There are 2 API methods which Algolia provides:

https://www.algolia.com/doc/api-reference/api-methods/save-objects/

> Adds or replaces records.
> 
> Adds records to an [index](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/prepare-data-in-depth/#algolia-index) or replaces them.
> 
> If a record doesn’t contain an objectID, Algolia automatically adds it. If you specify an existing objectID, it completely replaces all the attributes except for objectID.
> 
> To update only some attributes of an existing record, use [partialUpdateObjects](https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/) instead.

https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/

> Update one or more attributes of records.
> 
> Use this method to add or update attributes of one or more records, without replacing the whole record.
> 
>     If you provide an objectID that exists in your index, this method adds or updates the attributes of that record, without affecting the other attributes. To replace whole records, use the [saveObjects](https://www.algolia.com/doc/api-reference/api-methods/save-objects/) method instead.
> 
>     If you provide an objectID that doesn’t exist in your index, and the createIfNotExists parameter is true, this method creates a new record.
> 
>     If you call this method on an index that doesn’t exist yet, this method creates a new index.
> 
>     You can’t partially update nested attributes. If you specify a nested attribute, this method replaces the first-level ancestor. To update nested attributes, use the [saveObjects](https://www.algolia.com/doc/api-reference/api-methods/save-objects/) method. To retrieve the record’s data, use the [getObjects](https://www.algolia.com/doc/api-reference/api-methods/get-objects/) method.

**Comment by curquiza** [comment]
Thanks for the research!

Yes that's why we choose to use our POST method which is the equivalent of Algolia's `saveObject`

**Comment by daFish** [comment]
@curquiza Any thing I can do to use always PUT? I tried it locally and adding new and updating existing documents using only PUT seems to be supported (with Meilisearch 1.5.).

**Comment by curquiza** [comment]
@norkunas what would suggest as a solution for this? 😊
If no workaround exist, how could we update the symfony package?

**Comment by norkunas** [comment]
There are two solutions that I can think of:
 - global config value for every document indexing to use `updateDocuments` from [meilisearch/meilisearch-php](https://github.com/meilisearch/meilisearch-php)
 - allow to define same thing for each index, then somehow in `Meilisearch\Bundle\Engine::index` would fetch that config value for which method to use

**Comment by norkunas** [comment]
Some workarounds exists:
 - Intercept requests via http client and change request;
 - Override `Meilisearch\Client` and `HandlesDocuments::addDocuments` method;

Maybe there are more

**Comment by daFish** [comment]
@norkunas Thanks for the workarounds. I'm currently patching the `HandlesDocuments`-trait and will see how this works out.

**Comment by daFish** [comment]
Small update from my side: With this fix https://github.com/meilisearch/meilisearch/pull/4539 my issue vanished. So this issue can be closed.

**Comment by Adaphath** [comment]
Hi there,
I want to add custom fields outside the entity to Meilisearch with this bundle.
As mentioned before the POST method is used.

Did anyone find a solution to exchange POST with PUT?
I tried overriding some methods but never found a solid solution.
