### ISSUE TITLE
Test CI is now failing without any merge into the repo

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-symfony#327]
- First attempt last week: all green -> https://github.com/meilisearch/meilisearch-symfony/actions/runs/8233944664/attempts/1
- I re-ran the CI today: failing -> https://github.com/meilisearch/meilisearch-symfony/actions/runs/8233944664

```
 Script SYMFONY_DEPRECATIONS_HELPER='ignoreFile=./tests/baseline-ignore' ./vendor/bin/simple-phpunit --colors=always --verbose handling the test:unit event returned with error code 1
Error: Process completed with exit code 1.
```

Looks it's related to deprecation making tests failing, but I might be wrong. I'm not a symfony user.

Any contribution to remove/update them is welcome ❤️

**Comment by curquiza** [comment]
@norkunas maybe it's a 2sec guess for you 😇

**Comment by norkunas** [comment]
That deprecation should be added to baseline or configuring that setting in tests to avoid it :)

**Comment by norkunas** [comment]
The good thing about this that we can catch it early :)

**Comment by curquiza** [comment]
I feel hard we prevent merging PRs and releasing just because we have a deprecated 😅

**Comment by norkunas** [comment]
But its easy and fast fix :) will fix it tommorrow
