### ISSUE TITLE
CI is broken without changing anything

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-symfony#330]
CI is now failing, but was completely green two weeks ago

On the same commit, [attempt 1](https://github.com/meilisearch/meilisearch-symfony/actions/runs/8408735746/attempts/1)

<img width="1443" alt="Capture d’écran 2024-04-05 à 19 03 07" src="https://github.com/meilisearch/meilisearch-symfony/assets/20380692/01d56c86-7e3d-46cb-b5d8-887118009cfc">

[Attempt 2](https://github.com/meilisearch/meilisearch-symfony/actions/runs/8408735746):

<img width="1456" alt="Capture d’écran 2024-04-05 à 19 03 15" src="https://github.com/meilisearch/meilisearch-symfony/assets/20380692/a7699fa0-49de-4e98-8957-d34beb51a808">

Here is the error

<img width="1137" alt="Capture d’écran 2024-04-05 à 19 04 43" src="https://github.com/meilisearch/meilisearch-symfony/assets/20380692/7b76256c-2d0d-4f24-8e83-cc61c95e73f1">

We merged a PR recently, but the CI succeeded: https://github.com/meilisearch/meilisearch-symfony/pull/329

If someone has any clue.

@norkunas if you are around 😇

**Comment by norkunas** [comment]
This is because Symfony Serializer has a bug, nothing we can do about it, and people should add conflicts in their projects with that version :)

**Comment by Chris53897** [comment]
Should be fixed now with Symfony 7.0.7.
