### ISSUE TITLE
Memory leak on import command

### ISSUE THREAD

**Issue by johndodev** [meilisearch/meilisearch-symfony#350]
Hello, 

**Description**
Very simple use case, already done that on others projects (not recently, not the same amount of datas, and probably not the sames versions of all used bundles like doctrine, ..)

Just trying to push my initial datas. 

I created a custom normalizer, return a little array, nothing weird.

Output on a full import : 

```
... [multiple batch]
Indexed a batch of 500 / 500 App\Entity\Event entities into ac_dev_events index (13500 indexed since start)
Indexed a batch of 500 / 500 App\Entity\Event entities into ac_dev_events index (14000 indexed since start)
Indexed a batch of 500 / 500 App\Entity\Event entities into ac_dev_events index (14500 indexed since start)

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in [path]/vendor/doctrine/orm/src/Internal/Hydration/SimpleObjectHydrator.php on line 164

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 65536 bytes) in [path]/vendor/composer/ClassLoader.php on line 582
```

In dev, I have also memory limit, not same files but probably not relevant : 

```
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in [path]\vendor\doctrine\orm\src\Internal\Hydration\AbstractHydrator.php on line 617

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in [path]vendor\symfony\error-handler\Error\OutOfMemoryError.php on line 1
```

**Environment:**
- OS: linux
- Meilisearch version: v1.5.1
- meilisearch-symfony version: v0.15.4

Composer : 
- doctrine/dbal: 3.9.1
- doctrine/doctrine-bundle: 2.13.0

It would be weird that I'm the only one, maybe the problem is code here, but I don't really know where to look, since it's pretty straight forward.

Any ideas ?

**Comment by norkunas** [comment]
Hi,
Maybe your entities contains a lot of relations that are loaded on indexing?

**Comment by johndodev** [comment]
Not really, and I just tried with another entity, with the normalizer returning an 1 key array (with "id"), still memory leak. after ~40k loaded entities on UnitOfWork.php line 3174.

Even if lot of relations, $em->clear is supposed to clear stuff I think ? Something probably prevent doctrine / php to gc the entities somewhere... Problem is I'm pretty new in the project (didn't write all the code), but I don't see anything which could explain that yet.

**Comment by johndodev** [comment]
So, I looked on MeilisearchImportCommand.php, and I don't understand where the clear() is, it's called outside the "do while" loop, it may be an error ?
When I put it after the `++$page;`, the memory error is gone.

https://github.com/meilisearch/meilisearch-symfony/blob/main/src/Command/MeilisearchImportCommand.php#L147
