### ISSUE TITLE
Composer installation fails with missing ENV entries

### ISSUE THREAD

**Issue by althaus** [meilisearch/meilisearch-symfony#55]
Hey,

I've stumbled upon this project and as it looks quite promising, I've just gave it a try.

Sadly following the wiki just fails as running

~~~
composer require meilisearch/search-bundle symfony/http-client nyholm/psr7
~~~

will run into an 'Environment variable not found: "MEILISEARCH_URL".' error and composer will revert the changes.

So you have have to use the `--no-scripts` option or pre-define the ENV values. Maybe you'd like to update the wiki. On the other side I'd be great if a recipe could configure the .env automatically.

Kind regards
Matthias

**Comment by curquiza** [comment]
Hello Matthias!
I've just tried (with no MEILISEARCH_URL env variable) and I did not get any error...

I did:
```bash
$ mdkir test-symfony
$ cd test-symfony
$ composer init
...
[enter to everything except "Would you like to define your dependencies (require) interactively" where I put "no"]
...
$ composer require meilisearch/search-bundle symfony/http-client nyholm/psr7
```

**Comment by althaus** [comment]
Hmm... I've added it to my exsting project and it failed. :/

At the end it wasn't hard to fix, so feel free to close the iusse... on the other hand adding a Symfony Flex Recipe could enhance the UX|DX for this package a lot: https://github.com/symfony/recipes/blob/master/README.rst

**Comment by curquiza** [comment]
I still think this is weird I did not get any issue because you're right, it should fail. I will take time to investigate it, so I will not close the issue for the moment, we could get other feedbacks 👍

**Comment by codedge** [comment]
I installed the this package to today and could not find any issue installing it. I ran the command from the docs `composer require meilisearch/search-bundle nyholm/psr7` (already had `symfony/http-client` installed) and no error was shown.

@curquiza Adding a Symfony recipe would indeed be a good thing. It could automatically add 

```
###> meilisearch/meilisearch-bundle ###
MEILISEARCH_URL=http://127.0.0.1:7700
MEILISEARCH_API_KEY=
###< meilisearch/meilisearch-bundle ###
```
to the `.env` file, as other recipes do that. But this could be done in another issue.

**Comment by curquiza** [comment]
Thanks for your feedback @codedge! You're both right, I'm opening right now the issue!

**Comment by curquiza** [comment]
Closing this issue, but feel free to ping me if we need to remove it. 
FYI I opened #78 about the recipes!
