### ISSUE TITLE
Document "Listen to postRemove event"

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-symfony#97]
When #96 is merged, we need to update [this section of the wiki](https://github.com/meilisearch/meilisearch-symfony/wiki/index-data-into-meilisearch#indexing-automatically-via-doctrine-events)

**Comment by brunoocasali** [comment]
The `postRemove` was not added to the bundle, so we can close this.

Based on this comment: https://github.com/meilisearch/meilisearch-symfony/pull/96#issuecomment-866800227
